Common:
  profile: prod
EmitFlesti:
  period_minutes: 1
SummaryWriter:
  path: work/summary
StatusWriter:
  path: work/status
Market:
  exchanges:
    -
      name: KuCoin
      API-KEY: ***REMOVED***