# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#fail_fast: True
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
        - id: check-docstring-first
          types: [python]
        - id: trailing-whitespace
          args: [--markdown-linebreak-ext=md]
          types: [python]
        - id: check-executables-have-shebangs
        - id: check-case-conflict
          types: [python]
        - id: check-toml
        - id: check-yaml
          exclude: catalog-info.yaml
        - id: check-ast
          types: [ python ]
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.9.0
      hooks:
        - id: python-use-type-annotations
          types: [python]
        - id: python-no-log-warn
          types: [python]
    - repo: https://github.com/python/black
      rev: 22.8.0
      hooks:
        - id: black
          args: ["--safe", "--line-length=240"]
    - repo: https://github.com/PyCQA/flake8
      rev: 5.0.4
      hooks:
        - id: flake8
          types: [python]
          args: ["--max-line-length=240"]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
        - id: check-ast
          types: [python]
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v0.971'
      hooks:
        - id: mypy
          args: ["--ignore-missing-imports"]
          additional_dependencies: ['types-toml', "types-redis"]
          #exclude: "elena"
