LocalLogger:
  level: INFO
  path: logs  # relative path under home directory
LocalBotManager:
  path: bots # relative path under home directory
CctxExchangeReader:
  fetch_ohlcv_limit: 100
  fetch_ohlcv_limit_retry_every_milliseconds: 1000
CctxOrderManager:

