name: Makefile CI

on:
  push:
    branches: [ "main", "dev", "29-cicd-minimal-testing" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    #- name: configure
    #  run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make test

    - name: Run distcheck
      run: make release
